### Upload de Imagem
POST http://localhost:3001/upload
Content-Type: application/json

{
  "image": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
  "customer_code": "132",
  "measure_datetime": "2023-01-01T00:00:00.000Z",
  "measure_type": "GAS"
}

### Confirmar Medida
PATCH http://localhost:3001/confirm
Content-Type: application/json

{
  "measure_uuid": "692a380d-1727-414b-a834-7d22a9190f8e",
  "confirmed_value": 123.45
}

### Listar Medidas
GET http://localhost:3001/129/list?measure_type=GAS
Content-Type: application/json