### Upload de Imagem
POST http://localhost:3001/upload
Content-Type: application/json

{
  "image": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
  "customer_code": "132",
  "measure_datetime": "2023-01-01T00:00:00.000Z",
  "measure_type": "GAS"
}

### Confirmar Medida
PATCH http://localhost:3001/confirm
Content-Type: application/json

{
  "measure_uuid": "27d28726-a376-43ea-9160-69303d0f99d4",
  "confirmed_value": 68
}

### Listar Medidas
GET http://localhost:3001/129/list?measure_type=GAS
Content-Type: application/json