version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: measures
    ports:
      - "3307:3306"  # Mapeando a porta 3306 do contêiner para a porta 3307 no host
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build: .
    command: sh -c "npm install && npx prisma migrate deploy && npm run dev"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/measures
    ports:
      - "3001:3000"  # Mapeando a porta 3000 do contêiner para a porta 3001 no host
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data: